### ISSUE TITLE
Campaigns - Interventions functions documented

### ISSUE THREAD

**Issue by braybaud** [InstituteforDiseaseModeling/dtk-tools-malaria#31]

**Comment by JSchripsema-IDM** [comment]
I'm going to set up the basic infrastructure for pulling the docstrings into the Sphinx docs before I tackle this.

- [ ] Update Sphinx config for autodoc
- [ ] Pull in existing dtk-tools master and dtk-tools-malaria docstrings, reformatting to fix build errors
- [ ] Add documentation for all interventions functions

I will create new tickets for other functions that need new documentation.

**Comment by JSchripsema-IDM** [comment]
@braybaud I still have some reformatting of docstrings to do, but I have the Sphinx automation set up with the exception of the following warnings that have something to do with the code. I managed to solve the other import errors using either autodoc_mock_imports or apidoc_excluded_paths in the conf.py file, but can't get MAP and neighbors happy. You can see my doc repo changes here: https://github.com/JSchripsema-IDM/Documentation/tree/dtk-tools

WARNING: missing attribute mentioned in :members: or __all__: module dtk, attribute generic
WARNING: missing attribute mentioned in :members: or __all__: module dtk, attribute interventions
WARNING: missing attribute mentioned in :members: or __all__: module dtk, attribute tools
WARNING: missing attribute mentioned in :members: or __all__: module dtk, attribute utils
WARNING: missing attribute mentioned in :members: or __all__: module dtk, attribute vector
WARNING: missing attribute mentioned in :members: or __all__: module dtk.tools, attribute climate
WARNING: missing attribute mentioned in :members: or __all__: module dtk.tools, attribute demographics
WARNING: missing attribute mentioned in :members: or __all__: module dtk.tools, attribute separatrix
WARNING: missing attribute mentioned in :members: or __all__: module dtk.tools, attribute spatialworkflow
WARNING: autodoc: failed to import module 'MAP' from module 'dtk.tools.demographics'; the module executes module level statement and it might call sys.exit().
WARNING: autodoc: failed to import module 'neighbors' from module 'dtk.tools.demographics'; the following exception was raised:
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\sphinx-1.8.2-py3.6.egg\sphinx\ext\autodoc\importer.py", line 154, in import_module
    __import__(modname)
  File "c:\github\dtk-tools\dtk\tools\demographics\neighbors.py", line 10, in <module>
    with open('cache/raster_nodes_Haiti.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cache/raster_nodes_Haiti.json'
